[2025-09-24T09:15:02.328-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-24T09:15:02.349-0300] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WorkOrders.WorkOrders scheduled__2025-09-23T12:15:00+00:00 [queued]>
[2025-09-24T09:15:02.356-0300] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WorkOrders.WorkOrders scheduled__2025-09-23T12:15:00+00:00 [queued]>
[2025-09-24T09:15:02.356-0300] {taskinstance.py:2884} INFO - Starting attempt 1 of 1
[2025-09-24T09:15:02.382-0300] {taskinstance.py:2907} INFO - Executing <Task(_PythonDecoratedOperator): WorkOrders> on 2025-09-23 12:15:00+00:00
[2025-09-24T09:15:02.392-0300] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=184) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-24T09:15:02.394-0300] {standard_task_runner.py:72} INFO - Started process 186 to run task
[2025-09-24T09:15:02.394-0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'WorkOrders', 'WorkOrders', 'scheduled__2025-09-23T12:15:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/Example.py', '--cfg-path', '/tmp/tmpg7laxjw1']
[2025-09-24T09:15:02.396-0300] {standard_task_runner.py:105} INFO - Job 23: Subtask WorkOrders
[2025-09-24T09:15:02.456-0300] {task_command.py:467} INFO - Running <TaskInstance: WorkOrders.WorkOrders scheduled__2025-09-23T12:15:00+00:00 [running]> on host a44d6ec20546
[2025-09-24T09:15:02.534-0300] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WorkOrders' AIRFLOW_CTX_TASK_ID='WorkOrders' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T12:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T12:15:00+00:00'
[2025-09-24T09:15:02.535-0300] {taskinstance.py:740} INFO - ::endgroup::
[2025-09-24T09:15:07.010-0300] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2025-09-24T09:15:08.264-0300] {logging_mixin.py:190} INFO - 0 novas linhas para inserir.
[2025-09-24T09:15:08.265-0300] {logging_mixin.py:190} INFO - Nada a inserir. Encerrando.
[2025-09-24T09:15:08.265-0300] {python.py:240} INFO - Done. Returned value was: None
[2025-09-24T09:15:08.275-0300] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-09-24T09:15:08.276-0300] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=WorkOrders, task_id=WorkOrders, run_id=scheduled__2025-09-23T12:15:00+00:00, execution_date=20250923T121500, start_date=20250924T121502, end_date=20250924T121508
[2025-09-24T09:15:08.356-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-24T09:15:08.368-0300] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-24T09:15:08.373-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
