[2025-09-23T21:51:55.560-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-23T21:51:55.580-0300] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WorkOrders.run_main manual__2025-09-24T00:51:52.816981+00:00 [queued]>
[2025-09-23T21:51:55.587-0300] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WorkOrders.run_main manual__2025-09-24T00:51:52.816981+00:00 [queued]>
[2025-09-23T21:51:55.587-0300] {taskinstance.py:2884} INFO - Starting attempt 1 of 1
[2025-09-23T21:51:55.610-0300] {taskinstance.py:2907} INFO - Executing <Task(_PythonDecoratedOperator): run_main> on 2025-09-24 00:51:52.816981+00:00
[2025-09-23T21:51:55.619-0300] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=78) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-23T21:51:55.622-0300] {standard_task_runner.py:72} INFO - Started process 80 to run task
[2025-09-23T21:51:55.621-0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'WorkOrders', 'run_main', 'manual__2025-09-24T00:51:52.816981+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/Example.py', '--cfg-path', '/tmp/tmp80tjn8g4']
[2025-09-23T21:51:55.623-0300] {standard_task_runner.py:105} INFO - Job 14: Subtask run_main
[2025-09-23T21:51:55.689-0300] {task_command.py:467} INFO - Running <TaskInstance: WorkOrders.run_main manual__2025-09-24T00:51:52.816981+00:00 [running]> on host 29b76035fcd4
[2025-09-23T21:51:55.770-0300] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WorkOrders' AIRFLOW_CTX_TASK_ID='run_main' AIRFLOW_CTX_EXECUTION_DATE='2025-09-24T00:51:52.816981+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-24T00:51:52.816981+00:00'
[2025-09-23T21:51:55.772-0300] {taskinstance.py:740} INFO - ::endgroup::
[2025-09-23T21:52:00.255-0300] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2025-09-23T21:52:01.539-0300] {logging_mixin.py:190} INFO - 0 novas linhas para inserir.
[2025-09-23T21:52:01.539-0300] {logging_mixin.py:190} INFO - Nada a inserir. Encerrando.
[2025-09-23T21:52:01.540-0300] {python.py:240} INFO - Done. Returned value was: None
[2025-09-23T21:52:01.550-0300] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-09-23T21:52:01.551-0300] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=WorkOrders, task_id=run_main, run_id=manual__2025-09-24T00:51:52.816981+00:00, execution_date=20250924T005152, start_date=20250924T005155, end_date=20250924T005201
[2025-09-23T21:52:01.618-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-23T21:52:01.631-0300] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T21:52:01.645-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
